services:
  test:
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile.test
    profiles:
      - all
      - test
    command: "go test github.com/htchan/UserService/backend/internal/utils \
      github.com/htchan/UserService/backend/internal/grpc \
      github.com/htchan/UserService/backend/pkg/users \
      github.com/htchan/UserService/backend/pkg/services \
      github.com/htchan/UserService/backend/pkg/tokens \
      github.com/htchan/UserService/backend/pkg/permissions \
      github.com/htchan/UserService/backend/pkg/http \
      github.com/htchan/UserService/backend/cmd -v"